### ISSUE TITLE
Smooth shading does not exist.

### ISSUE THREAD

**Issue by notfrying1pans** [ThatCanadianEh/HLMVPlusPlus-IssueTracker#2]
Bug carried over from standard HLMV

**Comment by ThatCanadianEh** [comment]
Do you mean mat_fullbright?

**Comment by notfrying1pans** [comment]
meant this sorry
![image](https://user-images.githubusercontent.com/49667761/208272208-4b229983-38ea-4924-8b47-711996f48c55.png)

**Comment by ThatCanadianEh** [comment]
So it turns out this option is likely a GoldSrc leftover, and has never worked even in normal HLMV. It will likely be removed from that dropdown whenever the next test build drops.
